title: DangauSuluah
description: Pandagan abal-abal tentang sedikit hal.

collections:
  contents:
    output: true
    permalink: /contents/:name/

  concepts:
    output: true
    permalink: /concepts/:name/

markdown: kramdown
